### ISSUE TITLE
Stuck in config

### ISSUE THREAD

**Issue by jhanyk** [jrojko/hass_tecoapi#1]
Hi.

Can you describe a little bit in details where you do the configuration? I was able to install the Tecoapi, but I am not able to get any info pro the PLC.
Thank you for hint.

**Comment by z-vrba** [comment]
The same at my side. Have you managed that?
I have error:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tecoapi/binary_sensor.py", line 60, in async_setup_platform
    await async_setup_binary_sensor(hass, data, child_config, entities, objectid)
  File "/config/custom_components/tecoapi/binary_sensor.py", line 69, in async_setup_binary_sensor
    value = await data.async_get(TECOAPI_GETOBJECT, objectid, True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tecoapi/__init__.py", line 152, in async_get
    with async_timeout.timeout(DEFAULT_TIMEOUT_WAIT if wait else self.timeout, loop = self.hass.loop):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: timeout() got an unexpected keyword argument 'loop'`
